### PR TITLE
Transform gnet-allegro.scm into a module backend.

### PR DESCRIPTION
**Pull request by vzh**

### CODE REVIEW

**Comment by graahnul-grom** [comment]
`lepton-schematic` log at startup:

```
allegro: cannot load backend file
```

After clicking Netlist->allegro menu item:

```
allegro: error launching backend ('unbound-variable):
  (#f Unbound variable: ~S (allegro*) #f)
```

I would look at `(%search-load-path "gnet-allegro.scm")`
in the `(schematic netlist)` module.

**Comment by vzh** [comment]
It works for me, the log says:
> allegro: the output is written to [allegro.out]

You've probably `gnet-allegro.scm` left from previous installation in `/usr/local`.  Try to search for it first.  And, as always, delete your guile cache as well.

**Comment by graahnul-grom** [comment]
I do not use `/usr/local/`, always install to new folder.
Also, I do not use Guile cache (`$GUILE_AUTO_COMPILE=0`).
`Netlist->allegro` doesn't work. It cannot work.

In the `(schematic netlist)` module you are [loading](https://github.com/vzh/lepton-eda/blob/module-backend-allegro/libleptongui/scheme/schematic/netlist.scm#L40)
non-existing "gnet-allegro.scm" file.
It has been renamed to "allegro.scm" and converted
to module `(backend allegro)`.

Then, in `&netlist-allegro()`, the `allegro*()` function is [called](https://github.com/vzh/lepton-eda/blob/module-backend-allegro/libleptongui/scheme/schematic/netlist.scm#L50).
It cannot be found, because now it is exported in the
`(backend allegro)` [module](https://github.com/vzh/lepton-eda/blob/module-backend-allegro/liblepton/scheme/backend/allegro.scm#L29), which is not loaded at this point.

**Comment by graahnul-grom** [comment]
```diff
diff --git a/libleptongui/scheme/schematic/netlist.scm b/libleptongui/scheme/schematic/netlist.scm
index 6719f86f7..7049c2a30 100644
--- a/libleptongui/scheme/schematic/netlist.scm
+++ b/libleptongui/scheme/schematic/netlist.scm
@@ -23,6 +23,7 @@
   #:use-module (lepton page)
   #:use-module (netlist)
   #:use-module (netlist schematic)
+  #:use-module (backend allegro)
 
   #:export (&netlist-allegro))
 
@@ -34,14 +35,6 @@
   (make-toplevel-schematic (map page-filename (active-pages)))
 )
 
-;;; First load allegro backend code in order to use `allegro*'
-;;; below.
-(let
-  ((fpath (%search-load-path "gnet-allegro.scm")))
-  (if fpath
-    (primitive-load fpath)
-    (log! 'warning "allegro: cannot load backend file")))
-
 ;;; Allegro backend
 (define (&netlist-allegro)
   (catch #t
```

[vzh_1009_allegro.diff.txt](https://github.com/lepton-eda/lepton-eda/files/11092778/vzh_1009_allegro.diff.txt)
[0001-gui-Use-backend-allegro-module.patch.txt](https://github.com/lepton-eda/lepton-eda/files/11092782/0001-gui-Use-backend-allegro-module.patch.txt)

**Comment by vzh** [comment]
Ah, OK, sorry, it's my fault.  I had `gnet-allegro.scm` still installed in my `/usr/local`.  I've applied your fix, thank you!

**Review by graahnul-grom — APPROVED** [review]

**Pull request merged**
