### PR TITLE
lepton-schematic main menu updates

### LINKED ISSUE #225: Reorganize the main menu
A. `File` menu:
  1. delete duplicated `Revert` (already in `Page` menu)

B. `Edit` menu:
  1. combine to one item: `Object Properties...`:
    - `Color...`
    - `Line Width & Type...`
    - `Fill Type...`
    - `Pin Type...`

C. `View` menu:
  1. rename: `Sidebar` => `Right Dock`
  2. rename: `Status` => `Bottom Dock`

D. `Page` menu:
  1. separate `Revert` from the other items
  2. rename: `Revert` => `Revert...`

E. `Hierarchy` menu:
  1. delete duplicated `Documentation...` (already in `Help` menu)

F. `Options` menu:
  1. delete obsolete `Text Size...` item
  2. rename/rearrange, for example:
    - `Snap Grid Spacing...` => `Options...`
    - [separator]
    - `Scale up Grid Spacing` => `Grid +`
    - `Scale down Grid Spacing` => `Grid -`
    - [separator]
	- `Cycle grid styles` => `Grid style: cycle Dots/Mesh/Off`
    - `Toggle Snap On/Off` => `Grid snap: cycle Grid/Resnap/Off`
    - [separator]
    - `Toggle Outline/Box` => `Feedback mode: Outline/Box`
    - `Toggle Net Rubberband` => `Net: Rubberband On/Off`
    - `Toggle Magnetic Net` => `Net: Magnetic On/Off`
    - [separator]
    - `Show Coords Window...` => `Coords Window`
    - `Show Log Window...` => `Log Window`

Comments:
- B.1: all that commands do exactly the same: show `Object` dialog
box (`x_widgets_show_object_properties()`).
- C.3: currently, there is no way to show `find text state` window
unless docking windows GUI is enabled. We need to add a new action,
e.g. `view-find-text-state`. **[done]**
- F.2: `Options` menu:

Any suggestions are welcome.

### PR DESCRIPTION
**Pull request by graahnul-grom**
Closes #225 

Screenshots (left - old, right - new):

1_menu_file_old_new

2_menu_edit_old_new

3_menu_view_old_new

4_menu_page_old_new

5_menu_add_old_new

6_menu_hier_old_new

7_menu_attr_old_new

8_menu_options_old_new

9_menu_help_old_new

### CODE REVIEW

**Comment by vzh** [comment]
Several various notes about the changes and related things:

* The *Attributes* menu: What do you think about adding **T I** shortcut (**t**ext **i**nvisible) to show/hide invisible text while keeping legacy (and very popular) **E N**? (Hmm, do we have such a possibility without creating a new menu? If not, we have to add it! :-) )

* The *View* menu: I would change *Right dock* to *Side dock*. Hope, some time in future the user will be able to choose where to place the dock.

* The *View* menu: What does *Find Text State* do there?
Should we rename it, e.g. to *Find Text Results* and move to the *Attributes* menu? Or even add a new *Text* menu to gather entries related to text there?

* The *Attributes* menu: I would exchange *Show Specific Text* and *Hide Specific Text* to show **T H** above **T Shift+H** as they logically follow.

* The *Attributes* menu: We don't have **T F** assignment, IIUC. Probably, it was used for *Text Font* for old pre-cairo fonts. Wouldn't it be better to use **T F** instead of **T Shift+F** now?

* The *Options* menu: Add **O F** for the *Font...* entry in the *Options* menu... Or, maybe better (?), move the entry to the *Attributes* (or *Text*) menu and resurrect the old **T F** shortcut, as I said in the above note.

* The *Options* menu: Show **O L** for *Log Window*. Why is it not shown while the shortcut works as expected?

* The *Help* menu: Why **Shift+H O** and not just **H O**? (BTW, the short-cut and the `show-component-documentation` procedure don't work for me. I tried it for a resistor component, and the procedure just shows `#t` in log, no messages, no browser or viewer windows opened. Could you confirm this?)

**Comment by graahnul-grom** [comment]
> * The _Attributes_ menu: What do you think about adding **T I** shortcut (**t**ext **i**nvisible) to show/hide invisible text while keeping legacy (and very popular) **E N**? (Hmm, do we have such a possibility without creating a new menu? If not, we have to add it! :-) )

`( global-set-key "E N" 'edit-show-hidden )`
`( global-set-key "T I" 'edit-show-hidden )`
works just fine.

> * The _View_ menu: I would change _Right dock_ to _Side dock_. Hope, some time in future the user will be able to choose where to place the dock.

OK. Docking widgets are on my TODO list.

> * The _View_ menu: What does _Find Text State_ do there?
Should we rename it, e.g. to _Find Text Results_ and move to the _Attributes_ menu? Or even add a new _Text_ menu to gather entries related to text there?

*Find Text Results* sounds better, of course. I'll change it. Since it shows the window,
I think it belong to the *View* menu, though, introducing a new menu (*Text*) is an
interesting idea. What items should it contain?
* Add text
* Edit text
* Hide specific text
* Show specific text
* Show/hide hidden text
* Find text
* ?..
WDYT?

> * The _Attributes_ menu: I would exchange _Show Specific Text_ and _Hide Specific Text_ to show **T H** above **T Shift+H** as they logically follow.

No problem, but what is the logic behind it?

> * The _Attributes_ menu: We don't have **T F** assignment, IIUC. Probably, it was used for _Text Font_ for old pre-cairo fonts. Wouldn't it be better to use **T F** instead of **T Shift+F** now?

Indeed.

> * The _Options_ menu: Add **O F** for the _Font..._ entry in the _Options_ menu... Or, maybe better (?), move the entry to the _Attributes_ (or _Text_) menu and resurrect the old **T F** shortcut, as I said in the above note.

I'd leave it in the *Options* menu (after all, it sets the `schematc.gui::font` configuration key). I'll add the **O F** shortcut. BTW, I wonder why do we have to assign a key to each and every action (even *Help->About*)?

> * The _Options_ menu: Show **O L** for _Log Window_. Why is it not shown while the shortcut works as expected?

My bad. Once again, while taking screenshots, I've commented out the inclusion of my custom keys file in `gschemrc`, but forgot to disable the *Bloody Lisp Plugin Pack for Lepton EDA*: one of the plugins reassigns **O L** to another action.

* The _Help_ menu: Why **Shift+H O** and not just **H O**? (BTW, the short-cut and the `show-component-documentation` procedure don't work for me. I tried it for a resistor component, and the procedure just shows `#t` in log, no messages, no browser or viewer windows opened. Could you confirm this?)

Will be **H O**.
On my system, if `$BROWSER` env. var. is set, *Help->Find Component Documentation* opens `$BROWSER` with google search page, otherwise one of the installed web browsers is launched (I don't know why a particular one is selected).
I have another issue with *Help* menu: if I choose one of the docs items (e.g. wiki), the browser is opened, but in "blocking" mode (`lepton-schematic` becomes unresponsive until the browser window is closed).

Thank you for the review!

**Comment by graahnul-grom** [comment]
Have some strange commit by github conflict editor... What was that?

**Comment by vzh** [comment]
I wouldn't use github conflict editor at all. It's not very smart and convenient, IMO. YMMV.
I could squash and apply your changes using the *fast-forward* way, if you don't mind.

**Comment by graahnul-grom** [comment]
> I wouldn't use github conflict editor at all. It's not very smart and convenient, IMO. YMMV.
> I could squash and apply your changes using the _fast-forward_ way, if you don't mind.

OK

**Comment by graahnul-grom** [comment]
@vzh thank you!

**Comment by graahnul-grom** [comment]
> if I choose one of the docs items (e.g. wiki), the browser is opened, but in "blocking" mode (lepton-schematic becomes unresponsive until the browser window is closed).

On Help->Find Component Documentation, the browser also blocks lepton-schematic GUI.

> BTW, which progs do you use to make screenshots?

`scrot` (with convenience wrapper script)

> :-) What's the Bloody Plugin?

Random helper tools for `gschem` (now `lepton-schematic`) I have developed over the last ~3 years (while trying to learn Scheme), now organized as plugins infrastructure. Interactive `ngspice` simulation, external tools, custom attribute colors, sets of attributes to show/hide, component modification upon addition (e.g. hide/show/promote attrs), increment/decrement standard values, etc etc.
Now I'm in the middle of modifying the configuration system and after it's done, I'm going to publish the `BLPP`  here on github. Maybe (I hope) it will be helpful for someone besides myself.

**Pull request closed without merging**
