### PR TITLE
lepton-netlist: Update Russian translation

### PR DESCRIPTION
**Pull request by vzh**
Localisation support has been reinstated in #589. Now, here is an updated translation into Russian.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
@vzh Unfortunately, I can't get translated messages on my system.
Haven't tried on Linux yet, though.
I set both `LC_ALL` and `LANG` environment variables
to `ru_RU.UTF-8`.
`LANG` works for other tools (e.g. lepton-schematic), but not
for `lepton-netlist`. The same with `symcheck` (#605). :-(

**Comment by vzh** [comment]
Please check that `@localedir@` has been replaced with a correct value in
the expression `(bindtextdomain %textdomain "@localedir@")` in `lepton-netlist`. Then, at least `lepton-netlist --help` should work :-) (Some messages have not been prepared for translation in the code.)

**Comment by graahnul-grom** [comment]
Yes, I have checked it. `@localedir@` was correctly replaced.

**Comment by vzh** [comment]
In output of `make` in `netlist/po` I see:
> test ! -f ./lepton-netlist.pot || \
  test -z "nl.gmo ru.gmo" || make nl.gmo ru.gmo

and then
> rm -f ru.gmo && /usr/bin/msgfmt -c --statistics --verbose -o ru.gmo ru.po

May it be that `ru.gmo` has not been re-created on your system?

**Comment by graahnul-grom** [comment]
*.gmo files are created. Strangely, if I delete them, then `make`
does nothing to re-generate these files.
I tried this also on Linux (antix), and still unable to get localized
messages from `lepton-netlist` (other tools are OK, running
`lepton-cli` with the same command gives translated output).

**Comment by vzh** [comment]
Hm, I see `antix` is based on `Debian stable`. I run `Debian` and anything is translated properly.  I would suggest to concentrate on the translation text and apply the branch in order to not get stuck here.  Besides, the issue will anyway be solved by moving netlister's Scheme modules to liblepton's directory along with all translation files, which I hope will happen in near future.

**Pull request merged**
