### PR TITLE
Gtk3 port: get rid of warnings on deprecated functions gtk_widget_override_font()

### PR DESCRIPTION
**Pull request by vzh**

### CODE REVIEW

**Comment by graahnul-grom** [comment]
Somehow the font size both in the log window and macro widget
is smaller with GTK3:

gtk2:
pr_914_logwnd_gtk2
gtk3:
pr_914_logwnd_gtk3

gtk2:
pr_914_macrownd_gtk2
gtk3:
pr_914_macrownd_gtk3

The font specified in settings is "Victor Mono Regular 11".

**Review by graahnul-grom — APPROVED** [review]

**Comment by vzh** [comment]
On my system, other fonts, including those in menus, status bar, and
tooltips, are smaller a little.  This can be seen on your screenshots as
well.  Seems, GTK2 and GTK3 libs just render things differently.

**Comment by graahnul-grom** [comment]
The screenshots have been taken with different
GTK font size settings.
If I set `gtk-font-name="Open Sans 14"` in config for both
GTK2* and GTK3*, menus and dialog boxes looks the same.
The font is smaller only in the log window and the `:` prompt.

(*) config files:
~/.gtkrc-2.0
~/.config/gtk-3.0/settings.ini

**Comment by vzh** [comment]
OK, I seem to have found the issue [here](https://stackoverflow.com/questions/41257101/setting-gtkentry-font-from-pango-fontdescription).  Please wait a bit :-)

**Pull request merged**
