### PR TITLE
Transform two Scheme scripts into a new module

### PR DESCRIPTION
**Pull request by vzh**
A new module, `(schematic refdes)`, has been made up from two scripts, `auto-refdes.scm` and `auto-uref.scm`.  Their main functions are exported in the module.

Affects #727

### CODE REVIEW

**Comment by graahnul-grom** [comment]
I've found an error in regexp in `auto-refdes-reset!()`:
should be
`^([^0-9]+)([0-9]+)(.*)$` `// Uxyz123 => Uxyz?`
not
`^([^0-9])+([0-9]+)(.*)$` `// Uxyz123 => z?`

[0001-schematic-Fix-regexp-in-schematic-refdes.patch.txt](https://github.com/lepton-eda/lepton-eda/files/8798352/0001-schematic-Fix-regexp-in-schematic-refdes.patch.txt)

**Review by graahnul-grom — APPROVED** [review]
I think it would be nice to integrate the auto refdes stuff with GUI someday.
And thank you for the new release! Frankly, I shouldn't have appeared in the contributor list; had almost no free time... :(

**Comment by graahnul-grom** [comment]
A minor remark. I wouldn't name a variable like some reserved word,
as in the `(schematic refdes)` module's code ("match", but there's a function `match()` in the `(ice-9 match)` module).
While it's possible, it could be confusing and error-prone.

[0001-schematic-Rename-a-variable-in-schematic-refdes.patch.txt](https://github.com/lepton-eda/lepton-eda/files/8798550/0001-schematic-Rename-a-variable-in-schematic-refdes.patch.txt)

**Comment by vzh** [comment]
> I think it would be nice to integrate the auto refdes stuff with GUI someday. And thank you for the new release! Frankly, I shouldn't have appeared in the contributor list; had almost no free time... :(

Agree on auto refdes in GUI, disagree on the contributor list :-)  Your commits are present in the recent release, and your work here is a great commitment by itself!

**Pull request merged**
