### PR TITLE
Rename gschlas directory

### PR DESCRIPTION
**Pull request by graahnul-grom**
Rename directory in `utils/`: `gschlas` => `schlas`.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
I see that you are busy with your `component-library` branch, but could you please take a minute and merge #374 ("Rename gschlas directory". The changes are trivial, just rename `utils/gschlas` to `utils/gschlas`), so that I can continue with `lepton-schlas`: remove unused functions and `system-gschlasrc`, like you did with `lepton-attrib`.

**Comment by graahnul-grom** [comment]
I see that you are busy with your `component-library` branch (very impressive, I track it, BTW), but could you please take a minute and merge #374 ("Rename gschlas directory". The changes are trivial, just rename `utils/gschlas` to `utils/schlas`), so that I can continue with `lepton-schlas`: remove unused functions and `system-gschlasrc`, like you did with `lepton-attrib`.

**Comment by graahnul-grom** [comment]
FU**ING github

**Comment by vzh** [comment]
Thank you, @graahnul-grom. I'm not so much busy with the branch as with my day job which gives me too little time to work on Lepton. Sometimes I have to work on weekends, too. At home, I have too little time to work as well, having a large family. In parallel I'm trying to update NEWS in a local branch with what has been already done. So I'm sorry that I could not find an hour to look at some of your work :-/

**Pull request merged**
