### PR TITLE
Obtain shared lib names with ldconfig

### PR DESCRIPTION
**Pull request by vzh**
The commit set (hopefully) fixes the issue reported by @bdale on gitter.  The issue manifests on Debian when a user installs Lepton from its Debian package and runs Lepton tools without development files for `libgtk`, `libglib`, and `libgobject` installed.  In such a case guile can't find those libraries as non-standard extensions are used for them (e.g. `.so.0`).

The only solution I found so far is using `ldconfig` to get filenames of the libraries.  Other tools like `ldd` or `objdump` may be unavailable and are not recommended for use in makefiles.  OTOH, despite of having been mentioned in `make` manual, the variable `$(LDCONFIG)` is not available during build on Debian.  Dealing with `ldconfig` the way as `libtool` internally does during compilation would be tedious. So I decided to implement a work-around for this with using a dedicated variable on configure stage.  Now, the user can do `./configure USE_LDCONFIG=/sbin/ldconfig ...` to trigger using ldconfig to retrive the library filenames.

Other improvements include moving most of the code dealing with m4 variables related to libraries to Scheme and encapsulating it in one module, `(lepton m4)`.  Another module, `(lepton ffi lib)` now contains the code dealing with dlopening of foreign libraries, which is now used by all Lepton tools instead of separate definitions in various places.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
Tested on FreeBSD and Cygwin. it works.

**Comment by vzh** [comment]
@graahnul-grom, thank you for testing it!

**Comment by bdale** [comment]
Did a test build.  Had to ignore some apparently unrelated test suite failures, managed to get to a .deb file turning off the test suite.  Installed, cleared the guile cache, and see this on startup of both lepton-schematic and lepton-attrib:

;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/bin/lepton-attrib
;;; compiling /usr/share/lepton-eda/scheme/lepton/ffi.scm
;;; WARNING: compilation of /usr/share/lepton-eda/scheme/lepton/ffi.scm failed:
;;; In procedure dlopen: file "libgtk-x11-2.0.so", message "libgtk-x11-2.0.so: cannot open shared object file: No such file or directory"
;;; WARNING: compilation of /usr/bin/lepton-attrib failed:
;;; Unbound variable: liblepton
Backtrace:
           3 (primitive-load "/usr/bin/lepton-attrib")
In ice-9/eval.scm:
   187:27  2 (_ _)
   223:20  1 (proc #<directory (guile-user) 7fdcfe576c80>)
In unknown file:
           0 (%resolve-variable (7 . liblepton_init) #<directory (gu…>)

ERROR: In procedure %resolve-variable:
Unbound variable: liblepton_init

**Comment by vzh** [comment]
@bdale, do you have any version of lepton already installed on your system?

**Comment by vzh** [comment]
@bdale, this message
> ;;; WARNING: compilation of /usr/share/lepton-eda/scheme/lepton/ffi.scm failed:
;;; In procedure dlopen: file "libgtk-x11-2.0.so", message "libgtk-x11-2.0.so: cannot open shared object file: No such file or directory"

tells us that lepton could not found proper gtk-2 library.

Could you please check the contents of `m4.scm` file created as I'll describe below?

On my system initially:
```
$ apt policy libgtk2.0-dev
libgtk2.0-dev:
  Installed: 2.24.33-2

$ apt policy libgtk-3-dev
libgtk-3-dev:
  Installed: (none)

$ apt policy guile-2.2-dev
guile-2.2-dev:
  Installed: (none)

$ apt policy guile-3.0-dev
guile-3.0-dev:
  Installed: 3.0.7-1+b1
```

I uninstalled any versions of Lepton already installed, then

```
$ git checkout obtain-shared-lib-names-with-ldconfig

$ rm -rf ~/.cache/guile/ccache/

$ autoreconf -ivf && ./configure USE_LDCONFIG=/sbin/ldconfig && make && sudo make install
```

After installation there should exist the file 
`${prefix}/share/lepton-eda/scheme/lepton/m4.scm`, on my system it is `/usr/local/share/lepton-eda/scheme/lepton/m4.scm`:

```
$ cat /usr/local/share/lepton-eda/scheme/lepton/m4.scm 

(define-module (lepton m4))
(define-public %m4-use-cygwin #f)
(define-public %m4-use-gtk3 #f)
(define-public %m4-liblepton-major 9)
(define-public %m4-libleptonattrib-major 3)
(define-public %m4-libleptongui-major 3)
(define-public %m4-liblepton-gettext-domain "liblepton")
(define-public %ldconfig-libglib "libglib-2.0.so.0")
(define-public %ldconfig-libgobject "libgobject-2.0.so.0")
(define-public %ldconfig-libgtk2 "libgtk-x11-2.0.so.0")
(define-public %ldconfig-libgtk3 "libgtk-3.so.0")
```

Please check the value of `%ldconfig-libgtk2`.  Is it an empty string `""`, or just `"libgtk-x11-2.0.so"` (without `.0` at the end)?  Or is it the same as in my case?  I'm just wondering if this is an issue with `ldconfig` on your system or something other.

**Comment by vzh** [comment]
OK, merge it, as @bdale said on gitter that it works.

**Pull request merged**
