### PR TITLE
gnetlist: Delete nets with "no connect" symbol.

### PR DESCRIPTION
**Pull request by graahnul-grom**
Issue #172.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
@vzh If I understand correctly, this patch is completely unacceptable: should I close the PR? By no means do I consider myself a skilled Scheme programmer; I simply tried to help our user, @mario-giovinazzo, with #172.

**Comment by graahnul-grom** [comment]
My thoughts on how it can be fixed:
1) introduce some global variable (option?) to determine
if *NC* symbols should be deleted
2) set that option to `TRUE` by default
3) check that variable in `gnetlist.scm` and if it's `TRUE`,
delete *NC* symbols
4) backends that need access to all nets can turn this option off
(e.g. `geda`, `drc2` backends)
5) modify misc/nc-*.sym to have only one attribute: `symbol=nc`,
check for its presence in nets-delete-not-connected()

What do you think?

**Comment by vzh** [comment]
@graahnul-grom I would suggest adding of two different accessor functions (probably supplied with two corresponding fields in the `schematic` record) yielding appropriate filtered or non-filtered connection lists. Or one function with an optional argument for the same goal. The backend writers could opt the function/option they need. Most of the lepton backends could use filtered lists while some general ones could use non-filtered connection lists. A command line option key to force filtered or non-filtered output would be of help, too.
As for the *nc-\*.sym* files, on this stage we could just add the new attributes without breaking anything else. Then there is no need to fix special uses defined previously in, say, the `drc2` backend.

**Comment by graahnul-grom** [comment]
@vzh The changes discussed above is implemented in the [tb_065_netlist_noconnect](https://github.com/graahnul-grom/lepton-eda/tree/tb_065_netlist_noconnect)
branch, please take a look.
Should I close this PR and open a new one?

**Comment by graahnul-grom** [comment]
So, I'm closing this PR and will open a new one using the branch
mentioned in the previous comment. We may continue the discussion there.

**Pull request closed without merging**
