### PR TITLE
Transform lepton-attrib into a Scheme script and library libleptonattrib

### PR DESCRIPTION
**Pull request by vzh**
- `lepton-attrib` has been transformed into a library and an
  executable script using Scheme FFI which loads it.
- GTK (and other) functions are now initialized in Scheme which
  allows us to use the library functions in other programs (and I
  tried this with `lepton-schematic`).
- Command line processing functionality has been reimplemented in
  Scheme.  The option `--quiet` has been thrown away.
- Opening of schematic pages and log initialization is now carried
  out in Scheme instead of C.
- `g_debug()` is now used for low level debugging in
  `libleptonattrib` (and to debug `liblepton`'s SMOBs) instead of
  defining the `DEBUG` variable for this.
- The procedure `process-gafrc()` from the module `(netlist)` has
  been moved to the module `(lepton rc)` to be available for other
  utilities.
- Some functions have been merged, removed, cleaned up, or moved
  to other places.
- Cleaned up whitespaces in some files.
- Fixed some comments and info in the About dialog.
- Some global variables have been removed to make the code more
  robust.
  
Please note: using Scheme FFI may allow us to separate our Scheme
and C code base and make our life a bit happier :-)

I need feedback on how/if this code now works for you, especially
`lepton-attrib`, and especially if you can try it on other OS's
than Linux, or on other architectures, or with other Guile
versions than mine (2.2).

### CODE REVIEW

**Comment by graahnul-grom** [comment]
An interesting experiment. I have to familiarize myself with
Guile FFI to understand all the machinery.
My observations so far (FreeBSD, guile 2.2.7):
- `lepton-attrib` works (if one could call what it's doing a 'work' :-))
- `(dynamic-link "libleptonattrib")` fails unless I set `$LD_LIBRARY_PATH`.
- `attrib/Makefile.am` contains the same error as in #645.
- `git status` shows a bunch of untracked files in `libleptonattrib/`
  after `make` (there's no `.gitignore` file).
- can't get localization to work with `lepton-attrib`.

I will RTFM about FFI and continue testing.

**Comment by vzh** [comment]
@graahnul-grom, thank you!  Please stay tuned, I'll add some fixes soon.
Localization of `lepton-attrib` itself is not working yet (and I am not sure what to do with it), while `libleptonattrib` should be localized, right? The latter misses ld version, which I'm going to fix just now, as well as the issues with `Makefile` and `.gitignore`.

**Comment by graahnul-grom** [comment]
Shouldn't "lepton-attrib" be added to `attrib/.gitignore`?

Why `libleptonattrib`'s version is `0.0.0`?
```
libleptonattrib.so -> libleptonattrib.so.0.0.0
libleptonattrib.so.0 -> libleptonattrib.so.0.0.0
libleptonattrib.so.0.0.0
```

**Comment by vzh** [comment]
Lib version should be fixed now.

**Comment by vzh** [comment]
Reinstated l10n, and it works for me :-)

**Pull request merged**
