### PR TITLE
Add accelerator keys to lepton-schematic dialogs

### PR DESCRIPTION
**Pull request by graahnul-grom**

### CODE REVIEW

**Comment by vzh** [comment]
@graahnul-grom, please update NEWS with changes here to accelerate new release preparation :-)

**Comment by vzh** [comment]
BTW, good PR description can go to NEWS unchanged.

**Comment by graahnul-grom** [comment]
> BTW, good PR description can go to NEWS unchanged.

`Add accelerator keys to lepton-schematic dialogs`
Do I have to describe what accelerator key is?

**Comment by vzh** [comment]
Probably not. You could just describe what dialogs are affected.

**Comment by graahnul-grom** [comment]
For `NEWS.md`:

To make it easier to navigate with keyboard, accelerator keys have been added
to the following dialogs: 
- `Single Attribute Editor`
- `Edit Attributes`
- `Select Component`
- `Add Text`
- `Edit Text`
- `Object Properties`
- `Options`
- `Arc Params`

**Comment by vzh** [comment]
OK, thanks!

**Pull request merged**
