### PR TITLE
Rename data subdirectory: "gEDA" => "lepton-eda"

### PR DESCRIPTION
**Pull request by graahnul-grom**
I have installed `lepton-eda` and `geda-gaf` with the same `$PREFIX` and so far everything is working fine. Continue testing.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
@vzh Could we turn the compatibility symbolic links off by default now?
Is it possible to merge the changes we have just discussed on the mailing list (store dialog geometry in a separate file; [wip_cfg_priv_split](https://github.com/graahnul-grom/lepton-eda/tree/wip_cfg_priv_split) branch)?

**Comment by vzh** [comment]
> @vzh Could we turn the compatibility symbolic links off by default now?

I think yes.

> Is it possible to merge the changes we have just discussed on the mailing list (store dialog geometry in a separate file; wip_cfg_priv_split branch)?

[The XDG spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) reads that *user-specific non-essential (cached) data* should be written to `$XDG_CACHE_HOME`. I think those data are just *user-specific* and *non-essential* (especially for users like me who use tailing WMs) :-)
Another question is how to name the file containing main window/dialogs data. I think, since the directory name already contains `lepton`, we could just use something like `window.conf` or something like this. WDYT?

P.S. If you open a new issue/PR, it'll be a better place to discuss the issue, and we could point the users who are interested in it to the discussion.

**Comment by graahnul-grom** [comment]
BTW, what window manager are you using?

**Comment by vzh** [comment]
dwm

**Pull request merged**
