### PR TITLE
fixed two NULL reference cases as per coverity 208936 204295

### PR DESCRIPTION
**Pull request by drforbin**
Vlad, please review these changes.

### CODE REVIEW

**Comment by vzh** [comment]
208936 has already been fixed in #617 and is waiting for review.
Please don't use C++ style comments ("//") in new code.  The recommended C style is described in the [CONTRIBUTING](https://github.com/lepton-eda/lepton-eda/blob/master/CONTRIBUTING.md) document.

**Comment by vzh** [comment]
You can amend your commit and do `git push --force-with-lease` to have your branch updated.

**Comment by vzh** [comment]
#617 has been fixed in the master branch.

**Comment by drforbin** [comment]
ok. no c++ comments. I didn't see you fixed it.

**Pull request closed without merging**
