### PR TITLE
Show/hide main menu items relevant to current settings

### PR DESCRIPTION
**Pull request by graahnul-grom**
- Show `Side Dock` and `Bottom Dock` menu items in the
`View` menu only if `[schematic.gui]::use-docks` is set to `true`.

- Show `Next Tab` and `Previous Tab` menu items in the
`Page` menu only if `[schematic.gui]::use-tabs` is set to `true`.

-  Do not use docking widgets by default (`[schematic.gui]::use-docks=false`)
(#369)

### CODE REVIEW

**Comment by vzh** [comment]
@graahnul-grom, your "human-readable" syntax always bugs me a little (sigh). I mean menu changes in your first commit here.  OK, tastes vary, and you may prefer other spaces and parens :-} While there usually are most widely used patterns in any language, there are always the people who don't like them. But why to fix something not broken, something that someone wrote and thought it's looking good for their taste (especially when this is done in some common way for this language, ubiquitous and present in many many lines of code, and when  there are many people who like such a representation, and it works)?  What's wrong with quasiquotes? They're present not only in Scheme. In many languages, they're just means to neaten the code representation, to make it shorter and cleaner in their appearance. Quasi-quotes are often easier to use than mere list creation procedures, why should our users and potential devs be ignorant of them? :-/

Well, fair enough... I value the functional part of your contributions and this is an inferior issue. Just some thoughts aloud. (Sorry, if too loud :-))

I haven't read the patch-set as a whole yet, sorry, so my "essential" (non-emotional :-)) notes could follow.

**Comment by vzh** [comment]
@graahnul-grom, please add a commit with NEWS update with regard to your changes here.

**Comment by vzh** [comment]
@graahnul-grom, it's up to you to decide if to merge this PR as is.  While I approved the functional part, the code style part bugs me a little, so I hope you'll come to a right decision yourself ;-)

**Comment by graahnul-grom** [comment]
@vzh I understand all of your points, and feel sorry that my changes makes you nervous. I just thought about two basic facts then: 1) we do not have GUI menu editor and 2) not everyone who uses lepton (myself included) is hardcore lisp hacker.

**Comment by vzh** [comment]
Really, I'm OK with your changes (and glad you're back here). Thank you for the contribution!

**Pull request merged**
