### PR TITLE
Split up system-gschemrc

### PR DESCRIPTION
**Pull request by graahnul-grom**
Distinct parts of the `system-gschemrc`
configuration file are moved to separate files
under `conf/schematic/` subdir. The code is copied
verbatim, so there are no functional changes.
These files are loaded from `system-gschemrc`:
- `attribs.scm`
- `deprecated.scm`
- `keys.scm`
- `menu.scm`
- `options.scm`
- `stroke.scm`

Extra bonus: now it's easy for the user to override certain aspects
of `lepton-schematic` behavior. For example, I can provide my own
menu and attributes files, place them to `conf/schematic/` subdir
located somewhere in the `%load-path` - и вуаля! - my custom menu
and desired set of attributes will be used. No need to edit system
configuration file.

### CODE REVIEW

**Comment by vzh** [comment]
The patch breaks menu localization for some reason.

**Comment by graahnul-grom** [comment]
@vzh Forgot to replace `system-gschemrc.scm` with `menu.scm` in `po/POTFILES.in`.

**Comment by vzh** [comment]
I cannot get why `*.desktop.in` were changed to `*.desktop.in.h`? Could you elaborate, please?

**Comment by graahnul-grom** [comment]
@vzh Strange, they shouldn't change.

**Comment by graahnul-grom** [comment]
@vzh I've updated the PR, please check if it works for you.

**Comment by vzh** [comment]
OK, thank you!

**Pull request merged**
