### PR TITLE
Source tree cleanup. Fix examples

### PR DESCRIPTION
**Pull request by graahnul-grom**
- remove 2 unused old scheme scripts, empty directories
- move the `bom` python script from `examples/lightning_detector` to `contrib/`
- make SPICE simulation work in `RF_Amp` and `TwoStageAmp` examples
- fix gTAG example script and configuration files
- update `README` files in `examples/` and `examples/gTAG`
- use one `Makefile` instead of three in `examples/RF_Amp` (also reduces the number of patches I have to maintain for the FreeBSD port :-))
- `CONTRIBUTING.md`: notes about trailing spaces and long file lists in makefiles

### CODE REVIEW

**Comment by vzh** [comment]
@graahnul-grom, thank you for the work! Though I would like to have more complex issues about simulation to be separated from others.  I have some issues with the simulation examples (haven't dug into it further yet).  Could you move those two commits that regard simulation into another PR? Then, things would run quicker :-)

**Comment by vzh** [comment]
BTW, your Scheme scripting example could go to a dedicated page in wiki. gEDA wiki contains a page about scripting, we could do anything like it, probably better, with real script examples. WDYT?

**Comment by graahnul-grom** [comment]
Moving commits to another PR would be real pain in the neck (I'm sorry!).
If, anyway, you have issues with SPICE simulation, it's a PR on its own.
The problem that I had while fixing examples is this: netlist (spice-sdb) fails to work
with sub-circuits (i.e. schematics containing `spice-subcircuit-LL-1.sym` symbol):
```
$ lepton-netlist -o - -g spice-sdb Q1.sch

Using SPICE backend by SDB -- Version of 4.28.2007
schematic-type = .SUBCKT Q1_MSA26F
Backtrace:
           6 (primitive-load "/home/dmn/lepton/bin.master/bin/lepton…")
           5 (%with-toplevel #<geda-toplevel 0x802a67540> #<procedur…>)
In ice-9/eval.scm:
    619:8  4 (_ #(#(#(#(#<directory (guile-user) 800731140>) #) #) #))
   293:34  3 (_ #(#(#<directory (guile-user) 800731140>) "Q1_MSA2…" …))
    159:9  2 (_ #(#(#(#<directory (guile-user) 800731140>) (# …)) #))
   223:20  1 (proc #(#(#(#<directory (guile-user) 800731140>) (…)) #))
In unknown file:
           0 (%resolve-variable (7 . ls) #<directory (guile-user) 80…>)

ERROR: In procedure %resolve-variable:
Unbound variable: ls
```
So I can't regenerate `Q1.cir` and `Q2.cir` in `RF_Amp`.

Wiki page with scripts would be nice, and I think your enlightening repo `gschem-goodies` can be of help here.
Another useful wiki page that (IMHO) should be created is "screenshots".
The first (?) one you can see [here](https://graahnul-grom.github.io/ss/index.html).

**Comment by vzh** [comment]
@graahnul-grom, I've merged all the commits but the two ones related to simulation. You can rebase the branch onto current master head to have just those two commits in the branch. Then there are variants of how to proceed: either you rename the branch and make another PR with issues you encountered and we close this one, or we continue here.

**Comment by vzh** [comment]
I can confirm crash on `RF_Amp`. Please see #474 with fix of the `spice-sdb` backend.

**Comment by graahnul-grom** [comment]
@vzh What issues do you have with simulation in `TwoStageAmp` and `RF_Amp`
examples? Does it work at all with these two commits applied?

**Comment by graahnul-grom** [comment]
The "Source tree cleanup" part of this PR has been merged.
Examples will be fixed in another PR.

**Pull request closed without merging**
