### PR TITLE
Add casts for gobject and its class

### PR DESCRIPTION
**Pull request by vzh**
This branch fixes another couple of errors reported by g++.

### CODE REVIEW

**Comment by vzh** [comment]
@peter-b Good point! I didn't even think of this :-) I'll try to review the code.

**Comment by vzh** [comment]
@peter-b Some parent classes are _Gtk_ classes having no such define macros like `G_OBJECT`. I assume there is no need to make them? And what to do in such cases: add explicit casts (e.g. for `GtkActionClass`) or leave `G_OBJECT_CLASS` as it is now. WDYT?

**Comment by peter-b** [comment]
The `G_DEFINE_TYPE` macro is a bit weird.  Some of the arguments it takes are treated as *strings* rather than as symbols.  So, for example, at the top of `gschem_action.c`, you could write:

```c
G_DEFINE_TYPE (GschemAction, gschem_action, GTK_TYPE_ACTION)
```

**Comment by vzh** [comment]
@peter-b I added a new commit and rebased the branch. All seem to work now. Please look if I did TRT. I have not changed two files (x_*.c) since they need more TLC, I think.
P.S. Thanks for your last comment that enlightened me :-)

**Pull request merged**
