### PR TITLE
Sch2pcb rewrite sch2pcb process element in scheme

### PR DESCRIPTION
**Pull request by vzh**
This is a follow-up of PRs #1008 and #1011.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
```
ERROR: Wrong type argument in position 1 (expecting POINTER_P): 1.No elements found, so nothing to do.
```

`sch2pcb -v -v` output is attached.

[pr1012_sch2pcb-v-v_out.txt](https://github.com/lepton-eda/lepton-eda/files/11185042/pr1012_sch2pcb-v-v_out.txt)

**Comment by graahnul-grom** [comment]
And it leaves incomplete `brd.pcb.tmp` file in current dir:

```
# release: pcb 1.99x
# To read pcb files, the pcb version (or the cvs source date) must be >= the file version
FileVersion[20070407]
PCB["" 600000 500000]
Grid[10000.000000 0 0 0]
Cursor[0 0 0.000000]
PolyArea[200000000.000000]
Thermal[0.500000]
DRC[1000 1000 1000 1000 1500 1000]
Flags("nameonpcb,uniquename,clearnew,snappin")
Groups("1,c:2:3:4:5:6,s:7:8")
Styles["Signal,1000,3600,2000,1000:Power,2500,6000,3500,1000:Fat,4000,6000,3500,1000:Skinny,600,2402,1181,600"]
Element(0x00 "ACY500.fp" "R1_U1" "1k" 0 0 0 100 0x00)
(
	Pin(0 41 55 30 "1" 0x101)
	Pin(500 41 55 30 "2" 0x01)
	ElementLine(0 41 125 41 10)
	ElementLine(375 41 500 41 10)
	ElementLine(125 0 375 0 10)
	ElementLine(375 0 375 82 10)
	ElementLine(375 82 125 82 10)
	ElementLine(125 82 125 0 10)
	Mark(0 41)
)
```

**Comment by graahnul-grom** [comment]
The sample project I'm testing with is available at
https://graahnul-grom.github.io/sch/index.html#hier

**Comment by vzh** [comment]
Hi @graahnul-grom.  I seem to have fixed it in the last commit.  Thank you for the report!

**Comment by graahnul-grom** [comment]
Also I noticed that sch2pcb always returns success
to the shell (`$?` is `0`), even if there are errors
reported in the output.

**Pull request merged**
