### PR TITLE
Convert backend/common/spice.scm to Guile module in lepton-netlist

### PR DESCRIPTION
**Pull request by graahnul-grom**

### CODE REVIEW

**Comment by vzh** [comment]
I would name the module `(spice common)`, that is, other way around, since `spice` here is the main word.

**Comment by graahnul-grom** [comment]
Agree: `(spice common)` is better.

**Comment by graahnul-grom** [comment]
@vzh What do you think about making `lepton-netlist` output to `stdout`
by default?

**Comment by vzh** [comment]
Yeah, I thought of it, too.  While I'm for it, we would better ask our user base on the `geda-user` list. Some people should have makefiles and scripts depending on the legacy functionality.

**Comment by graahnul-grom** [comment]
Agree. We should at least warn the users in advance on the mailing list.

**Pull request merged**
