### PR TITLE
Rename PAGE and GedaPage structures

### PR DESCRIPTION
**Pull request by vzh**
Changes like in #743 though for pages.

### CODE REVIEW

**Review by graahnul-grom — APPROVED** [review]
Are you going to also rename source files
(e.g. remove `geda_` and `gschem_` prefixes,
or change them)?

**Comment by vzh** [comment]
Yes, I am. Haven't decided what to do better yet: rename by dropping the prefixes or replace `geda` with `lepton`, `gschem` with `schematic` or something like this.  I believe it's a subject for discussion.  WDYT?

**Comment by graahnul-grom** [comment]
I think in most cases the prefix is redundant, probably
only makes sense when there are conflicts in file names.
Even header files are installed to dedicated subdirs,
`include/libleptonattrib/`, `include/liblepton/`, so
shouldn't clash with anything.

**Comment by vzh** [comment]
OK, let's get rid of them then.

**Comment by bdale** [comment]
dmn <notifications@github.com> writes:

> I think in most cases the prefix is redundant, probably
> only makes sense when there are conflicts in file names.

I agree.

Bdale

**Comment by vzh** [comment]
OK, thanks.  I've fixed my issue with `string.h` mentioned somewhere else by renaming it to `str.h`.

**Pull request merged**
