### PR TITLE
GTK3 support for lepton-gui

### LINKED ISSUE #681: Lepton should support GTK3 as well
It is one of Lepton goals. Moreover, @bdale reported on gitter:

```
Debian has started to tag packages that have a hard dependency on GTK version 2 with a bug.
```

### PR DESCRIPTION
**Pull request by vzh**
Together with #682 closes #681

### CODE REVIEW

**Comment by vzh** [comment]
I feel the best way to get some feedback here is to apply the commit set and make a new release (fixing bugs afterwards) :-)

**Comment by graahnul-grom** [comment]
After 5-10 seconds fiddling with GUI, lepton-schematic crashes.
In terminal I see "Gtk-CRITICAL" errors like these:
```
gtk_grid_attach: assertion 'GTK_IS_WIDGET (child)' failed
gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```

Also, tons of compiler warnings and malfunction in some GUI
elements (page manager, close confirmation dialog); ugly
tab header widgets.
FreeBSD 11.4, GTK 3.24.23, no gtk theme used.

**Comment by vzh** [comment]
Hi!
I've eventually prepared another, hopefully better commit set:
- All gtk3 code does not interfere with gtk2 one; it is carefully guarded by using of `#ifdef ENABLE_GTK3` guards.
- It includes a minimal set of changes to only support GTK 3.0.0, not any later version, so "tons of warnings" is predictable and expected.
- I haven't seen any critical GLib messages when used the compilation result yet (well, I hadn't seen any errors with `gtk_grid_attach` and `gtk_box_gadget_distribute` before, either, so YMMV).
- The only segfault I found could happen when I actively used page manager and opened/closed pages in a hierarchical schematic (not sure, if this could happen with non-hierarchical schematics).  I've fixed it.
- Some issues still exist.  I found some.  E.g. wrong zooming of the last page if you use tabs and open several schematics.  Another one is invisible widgets in the first tab of the right dock, where object properties live (if you enable docks, of course).

I propose to absorb and release the changes if there's no critical issues in the code, that may break GTK2 GUI.  I would be very glad to announce the change and receive more feedback from the users about any issues in the GTK3 support.

**Comment by graahnul-grom** [comment]
Титаническая работа, Володя. Совсем ты себя не бережёшь.
Здоровье-то - не казённое. :-) [1]
I think you are right: despite all the rough edges, we should release
these changes. It's hard for us to catch all the issues, so let those
interested in GTK3 GUI help us.
My observations so far (continue testing):
- I can no longer trigger crash when working with page manager
- there are no glib critical messages anymore
- yes, the "Object properties" dock widget is empty
- no icons in menus
- when detaching a menu:
```
*** BUG ***
In void pixman_region32_init_rect(region_type_t *, int, int, unsigned int, unsigned int): Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```
- files list in the close confirmation dialog is not redrawn when
you click "Show full paths", until dialog is resized manually.
- I can't get the "Close" tab button to draw properly:
gtk2:
tabs_gtk2
gtk3:
tabs_gtk3

- `git status` after `make`:
?? libleptongui/scheme/schematic/ffi/gtk.scm

[1] Please consider opening a donation mechanism of some sort
(I don't know anything about that), so that grateful users,
especially those who want gtk3 support,
can (at least) buy you a beer. :-)

**Comment by graahnul-grom** [comment]
> wrong zooming of the last page if you use tabs and open several schematics

Can't reproduce that.

**Comment by graahnul-grom** [comment]
> wrong zooming of the last page if you use tabs and open several schematics

Can't reproduce that.

**Comment by vzh** [comment]
@graahnul-grom,
Let's open new issues for bugs you found.

I've not managed to restore icons in menus.  Gtk currently goes other way, they claim they won't support icons in menus as superfluous.  Cannot say, that I understand my new accel label code enough to restore icons.

I hope other issues are solvable.

As for donations, I don't know what is needed for having them, never thought of that (despite I like beer very much ;-)).  GH sponsorship  doesn't work for Russia for some reason, either (I think because we're under sanctions?).

**Comment by graahnul-grom** [comment]
> they claim they won't support icons in menus

yes, of course, it's up to them to decide whether users want
icons in menus or not. I've told you, they're total nutcases. :)

so far, found this article:
https://itsfoss.com/open-source-funding-platforms/
nothing promising, it seems...

> because we're under sanctions?

because they're under hard drugs :-)

**Comment by graahnul-grom** [comment]
@vzh From what I have seen so far, it seems there's little sense
in dealing with those donation "umbrella" companies
(as in the link above).
Most people just put links to their e-money accounts
(PayPal, YandexMoney, etc.) or even credit card number
on their web pages. I think you should do the same thing.

**Pull request merged**
