### PR TITLE
Rename core modules

### PR DESCRIPTION
**Pull request by vzh**
- Renamed `(geda *)` and `(gschem *)` core modules.
- Updated NEWS.
- Added missing `(geda object)` tests.

Affects #39.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
```diff
diff --git a/schematic/src/g_hook.c b/schematic/src/g_hook.c
index 6e007a443..41c45e0de 100644
--- a/schematic/src/g_hook.c
+++ b/schematic/src/g_hook.c
@@ -28,7 +28,7 @@
 #include "gschem.h"
 
 SCM_SYMBOL (at_sym, "@");
-SCM_SYMBOL (gschem_sym, "gschem");
+SCM_SYMBOL (gschem_sym, "schematic");
 SCM_SYMBOL (core_sym, "core");
 SCM_SYMBOL (hook_sym, "hook");
 SCM_SYMBOL (run_hook_sym, "run-hook");
```

[4pr556.diff.txt](https://github.com/lepton-eda/lepton-eda/files/4164921/4pr556.diff.txt)

**Comment by vzh** [comment]
Thank you!

**Comment by vzh** [comment]
Please check if it works OK now.

**Comment by graahnul-grom** [comment]
I see no other issues with this PR.
Great job, thank you!

**Comment by graahnul-grom** [comment]
@vzh I was almost ready to make a PR fixing non-working REPL.
Luckily, I noticed the commit a2d55c0 above :-)

**Comment by graahnul-grom** [comment]
Could it be merged, please? Everything works fine, AFAICT.

**Comment by vzh** [comment]
Sure :-) (Just was very busy and then tired yesterday.)

**Comment by graahnul-grom** [comment]
We should add `lepton/core/gettext.scm` to `.gitignore`.

```diff
diff --git a/liblepton/scheme/.gitignore b/liblepton/scheme/.gitignore
index 572f8cf7d..a4d2b53c3 100644
--- a/liblepton/scheme/.gitignore
+++ b/liblepton/scheme/.gitignore
@@ -1,4 +1,5 @@
 Makefile
 Makefile.in
 test-suite.log
+lepton/core/gettext.scm
 *~
```

**Comment by vzh** [comment]
I don't mind.

**Pull request merged**
