### PR TITLE
Support of building GTK3 version of lepton-attrib

### PR DESCRIPTION
**Pull request by vzh**
Affects #681 
- Add a new option, `--with-gtk3` to enable build of the **GTK3** version of the program.
- Get rid of obsolete `gtkextra` code from `libleptonattrib`.
- Add section about `lepton-attrib` to the reference manual and README.md.
- Several cleanups.

New gtksheet code for GTK3 can be found here:
  https://github.com/fpaquet/gtksheet
With recent GCC you may need a patch from there: https://github.com/fpaquet/gtksheet/pull/33

### CODE REVIEW

**Comment by graahnul-grom** [comment]
I can build it with `gtkextra` for gtk2, but unable to test `--with-gtk3`.
There is no `gtksheet` package on my system. I've found the
[devel/spread-sheet-widget](https://www.freshports.org/devel/spread-sheet-widget/) port, but it's a completely different thing.
Unfortunately, I can't find `gtksheet` in Debian packages either
(https://www.debian.org/distrib/packages).

**Comment by graahnul-grom** [comment]
I noticed that on exit lepton-attrib does not prompt to save changes.
Continue testing.

**Comment by graahnul-grom** [comment]
@vzh It is very nice that you managed to get rid of `gtksheet`
code in lepton-attrib. +1.

**Comment by vzh** [comment]
@graahnul-grom, I forgot to add links here, please see updated description.  (AFAIR, the links are mentioned in the updated manual.)

**Comment by graahnul-grom** [comment]
Thanks, I've built fpaquet/gtksheet and lepton-attrib --with--gtk3,
though it's not possible to build the entire suite (`make` stops in
`libleptongui/`). After `make` error "unknown type name 'GdkDrawable'"
I run `make install` in `libleptonrenderer/`, `liblepton/` and
`libleptonattrib/`. After that I can run lepton-attrib.
The error mentioned above remains (no prompt to save changes).

**Comment by vzh** [comment]
I've described it in the manual and README :-)

**Comment by graahnul-grom** [comment]
For some reasons `cd libleptonattrib/ && make && sudo make install`
did not work for me. I had to run `make install` in the sequence I
described in my previous message.

**Comment by vzh** [comment]
You're right.  It's required to make `liblepton` and `libleptonrenderer` before `libleptonattrib`.

**Comment by graahnul-grom** [comment]
In [build instructions](https://graahnul-grom.github.io/ref-manual/lepton/Installation-of-lepton_002dattrib.html#Installation-of-lepton_002dattrib):
```
autoreconf -ivf && ./configure
cd libleptonrenderer/ && make && sudo make install
cd ../liblepton/ && make && sudo make install
cd ../libleptonattrib/ && make && sudo make install
```

```
# cd ../liblepton/ && make && sudo make install
geda_object_list.c:21:10: fatal error: version.h: No such file or directory
```

As I mentioned, I had to run `make` in the top-level directory first,
until it exits with error, so that it can generate `version.h`.

**Pull request merged**
