### PR TITLE
Fix coverity scan report 208936

### PR DESCRIPTION
**Pull request by vzh**

### CODE REVIEW

**Comment by vzh** [comment]
Mistakenly added commit with code from another branch, which is now fixed.

**Comment by graahnul-grom** [comment]
@vzh Please excuse my ignorance, but where can I find these
"coverity scan" reports?

**Comment by vzh** [comment]
[Here](https://github.com/lepton-eda/lepton-eda/wiki/Coverity-Scan) is some useful info.  (You have to sign up there first and request an approval of one of the project owners. I believe it's easy.)

**Comment by graahnul-grom** [comment]
Thank you, I've just sent the request ("add me to project" button).
Is there anything else I should do?

**Comment by vzh** [comment]
I've just confirmed your request, so it should just work now.  Please let me know if you encounter any issues.

**Pull request merged**
