### PR TITLE
Bump required version of GTK+.

### PR DESCRIPTION
**Pull request by vzh**
This is safe for most distributions these days.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
Vladimir, maybe we should bump versions of GTK dependencies, too?
From GTK+ 2.24.0 `INSTALL` file:
> GTK+ 2.24.0 requires at least
> - GLib 2.25.10
> - Pango 1.20
> - GdkPixbuf 2.21.0
> - ATK 1.29.2
> - cairo 1.6.0
> - gobject-introspection 0.9.3

**Comment by vzh** [comment]
Good point!
Currently our config is as follows:
- glib (and gio) >= 2.20.0
- pangocairo >= 0.26
- pango >= 1.23.0

**Comment by graahnul-grom** [comment]
By the way, what is `pangocairo`? Shouldn't that be `cairo` instead?

**Comment by vzh** [comment]
@graahnul-grom On my system:
> $ apt-cache search pangocairo
libpangocairo-1.0-0 - Layout and rendering of internationalized text
$ apt-cache depends libpangocairo-1.0-0
libpangocairo-1.0-0
  Depends: libc6
  Depends: libcairo2
  Depends: libfontconfig1
  Depends: libfreetype6
  Depends: libglib2.0-0
  Depends: libpango-1.0-0
  Depends: libpangoft2-1.0-0
  Breaks: libpango1.0-0
  Replaces: libpango1.0-0


AFAIUI, the `cairo` version is automatically checked in `AX_CHECK_CAIRO` as a dependency.  

Please check the updated commit.

**Comment by graahnul-grom** [comment]
All works fine.

**Pull request merged**
