### PR TITLE
Update translation files

### PR DESCRIPTION
**Pull request by graahnul-grom**

### CODE REVIEW

**Comment by graahnul-grom** [comment]
`$ find . -type d -name po`
./gnetlist/po
./liblepton/po
./symcheck/po
./cli/po
./gattrib/po
./schematic/po

Should I run `make update-po` in remaining `po` directories as well?

**Comment by vzh** [comment]
> Should I run make update-po in remaining po directories as well?

Yes, it would be nice :-)

**Comment by graahnul-grom** [comment]
Done:  #221

**Comment by vzh** [comment]
Thank you!

**Pull request merged**
