### PR TITLE
lepton-tragesym: fix the option 'generate_pinseq'

### PR DESCRIPTION
**Pull request by vzh**
Closes #520
Affects #492

### CODE REVIEW

**Comment by vzh** [comment]
Right.

**Comment by graahnul-grom** [comment]
@vzh I remember we have discussed renaming of `tragesym`
to `symgen`. Do you think it's worth it, or should we better
leave it alone?

**Comment by vzh** [comment]
We could rename it. However, I think, it would be reasonable in case we add some new functionality to it, e.g. support for other formats, other option names etc.  In the state it is, the program is just tragesym's sibling.

**Comment by graahnul-grom** [comment]
OK, agree, though it has been 100% rewritten. :-)

**Pull request merged**
