### PR TITLE
Fix the (gschem gschemdoc) module in lepton-schematic

### PR DESCRIPTION
**Pull request by graahnul-grom**
- Do not include `gschemdoc.scm` in the distribution tarball.
It should be regenerated by `make` from the `gschemdoc.scm.in`
template file. Otherwise, the documentation directory can be set
incorrectly.
Discovered while making [lepton-eda package for Slackware Linux](https://github.com/graahnul-grom/slackware-lepton-eda),
where documentation path is explicitly set
by the `--docdir` configure option.
- Do not use `error()` function if component's documentation
cannot be found (`Help->Find Component Documentation`), avoiding
backtrace in the log. Just show a message box.

### CODE REVIEW

**Comment by vzh** [comment]
Cool, many thanks!  Hope you publish the link on geda-user soon.

**Comment by graahnul-grom** [comment]
I've submitted `SlackBuild` to [slackbuilds.org](https://slackbuilds.org).
Now it's in the [pending](https://slackbuilds.org/pending/) queue.

**Comment by vzh** [comment]
Great!

**Comment by graahnul-grom** [comment]
[Committed](https://git.slackbuilds.org/slackbuilds/commit/?id=2a875507b86969cb5eae24f0373bee1040c28bc7) to the SlackBuilds.org repository ([development/lepton-eda](https://git.slackbuilds.org/slackbuilds/tree/development/lepton-eda)).
Lepton EDA [SlackBuilds.org page](https://slackbuilds.org/repository/14.2/development/lepton-eda/).

**Pull request merged**
