### PR TITLE
schematic: Rewrite x_event_button_released() in Scheme.

### PR DESCRIPTION
**Pull request by vzh**
- Several new accessors for `GschemToplevel`'s fields have been
  added and utilized in the code.
- Accessors for GDK key masks and some fields of the structure
  `GdkEvent` have been added so they are now available in Scheme.
- A new callback function, `callback-button-released()`, has been
  added as a substitute for `x_event_button_released()`.
  
Thus, mouse button release event processing is now carried out in Scheme,
which allows for further refactoring.

### CODE REVIEW

**Review by graahnul-grom — COMMENTED** [review]
The code of `x_event_button_released()` was straightforward
and relatively simple. Can't say the same about guile version. :-(

**Review by graahnul-grom — APPROVED** [review]

**Comment by vzh** [comment]
Well, yes, it's a subject for further refactoring.  OTOH, for now I'm pursuing two different goals: make mouse events available in Scheme for end users, which would facilitate scripting, and untangling/getting rid of Scheme-in-C code.  Please bear with me ;-)

**Comment by graahnul-grom** [comment]
OK :)

I think it would be helpful if we can identify parts of code that
should be rewritten in Guile in order to get rid of Scheme-in-C stuff.
Perhaps creating an issue for that.

**Comment by vzh** [comment]
In two words, the more the better :-)
Just git-grepping in the repository by `scm_` will give you a clue, the functions that have to be rewritten live in the following files:
```
liblepton/src/g_basic.c
liblepton/src/s_clib.c
liblepton/src/scheme_toplevel.c
libleptongui/src/g_action.c
libleptongui/src/g_hook.c
libleptongui/src/g_window.c
libleptongui/src/gschem_find_text_state.c
libleptongui/src/gschem_macro_widget.c
libleptongui/src/gschemhotkeystore.c
libleptongui/src/keys.c
libleptongui/src/schematic_hierarchy.c
```

Of course, many other functions depend on them, and I use top-down approach to reach them.

**Pull request merged**
