### PR TITLE
Fix crash in hotkeys dialog

### PR DESCRIPTION
**Pull request by graahnul-grom**
`lepton-schematic` crashes on attempt to open hotkeys dialog
from the new window (opened by `File->New Window`), when the
previous window is closed. `SIGSEGV` on Linux, `SIGBUS` on FreeBSD.
The problem is in `GschemHotkeyStore` code trying to do live
updates to the list of hotkeys. With that code simplified, the crash is gone.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
@vzh By the way, since 442e595 ("Fix define-action syntax...") there are no icons
nor action strings in the hotkeys dialog.

**Comment by vzh** [comment]
Could you please add an issue about it? I cannot fix it just now.

**Comment by graahnul-grom** [comment]
#433

**Comment by vzh** [comment]
#435 

BTW, if I build lepton with the changes there, I cannot reproduce the crash. Otherwise it is easily reproduced (well, really I had to open a third window to trigger the crash).

@dmn Could you check this?

Anyway, as your code simplifies the code :-) I won't mind to apply it in any case (just need a bit more time to read and understand it).

And a friendly advice: please rebase your branches more often onto master HEAD. It would avoid bit-rotting and make it easy to merge them without any GH involvement (sometimes it behaves in a not very smart way). And... please avoid trailing newlines in your commits ;-)

**Comment by graahnul-grom** [comment]
Checked out #435 - it works. It also fixes the crash (however, I would apply the patch anyway, since it removes unnecessary, complicated code).
And thank you for the good advice on rebasing: didn't think about that. Should
always remember that we are on GH here.

**Pull request merged**
