### PR TITLE
Fix rotation of logs.

### PR DESCRIPTION
**Pull request by vzh**
The issue is in using different functions for obtaining path of storing logs.

### CODE REVIEW

**Comment by vzh** [comment]
> Thank you. That log rotation stuff was completely overlooked.
> A couple of observations:
> 
>     * The `(geda log-rotate)` module has no public functions. `(use-modules (geda log-rotate))` will lead to code execution, IMHO, it's not a proper way to use guile modules.

Agreed. Moreover, if you'll look at the comments in `geda.scm`, you find the comment by @peter-b that reads:
```
;; Clean up logfiles
;; FIXME this should be a plugin
```
(Hmm, I don't quite understand what it means :-))


>     * It seems that we can get rid of `geda.scm` file (2 lines of code): it just loads the `(lepton library)` and `(geda log-rotate)` modules, it could be done in `system-gafrc`.

I would better get rid of `system-gafrc` and move any init functions into `lepton.scm` or `init.scm` as we discussed before, and move any config settings to `lepton-system.conf`...

**Comment by graahnul-grom** [comment]
Yes, `system-gafrc` should go away. As well as `system-gschemrc` (#511).
And let's rename `gafrc.d` directory. What name would you choose for it?

**Comment by vzh** [comment]
It's a difficult question for me since I never thought of it :-) So... dunno.

**Comment by graahnul-grom** [comment]
Could be something like `autostart`, `startup`, `autoload` or simply `rc.d`,
though the name `rc.d` is ambiguous: on some systems these directories
contains stuff that *could* be executed, but do not loaded automatically (BSD),
whereas on Linux `rcX.d` are startup directories.

**Comment by vzh** [comment]
Well, `autoload` seems to be the most appropriate name from all suggested since it wholly makes clear what it should be used for.

**Comment by graahnul-grom** [comment]
I agree.

**Comment by graahnul-grom** [comment]
Could we also rename `symbols/geda-clib.scm` to `config-sym-libs.scm`, for example (there is `config-netlist.scm` that goes to the same `gafrc.d/` folder)?
And since the `gafrc.d/` directory contains Scheme files, shouldn't it be installed
to `share/lepton-eda/scheme/` (`share/lepton-eda/scheme/autoload`)?

**Comment by vzh** [comment]
> Could we also rename `symbols/geda-clib.scm` to `config-sym-libs.scm`, for example (there is `config-netlist.scm` that goes to the same `gafrc.d/` folder)?

I would rename it to `config-symbol-libraries.scm`.  I better like words without abbreviations.

> And since the `gafrc.d/` directory contains Scheme files, shouldn't it be installed
> to `share/lepton-eda/scheme/` (`share/lepton-eda/scheme/autoload`)?

Fully agree with you.  Especially, 'cause we're going towards getting rid of any `*gafrc*` / `*gschemrc*` stuff.  I would prefer the second name (`autoload`).

**Pull request merged**
