### PR TITLE
Move utilities into separate directories under utils/

### PR DESCRIPTION
**Pull request by graahnul-grom**
@vzh What do you think about moving `lepton-netlist`
back to `netlist/` and `lepton-cli` to `utils/`?

Affects #732.

### CODE REVIEW

**Comment by vzh** [comment]
I'd prefer to keep both utilities in `utils/`.  The only thing I'm unsure is where to store backends.  Test suites could be merged and moved say to `build-aux` as `automake` suggests, but backends is a netlister property not very well integrated with `lepton-netlist` so I'm in doubt.

**Comment by vzh** [comment]
Thank you!

**Comment by graahnul-grom** [comment]
> I'd prefer to keep both utilities in utils/.

Don't you consider `netlist` as one of the core
components of the suite? :-)

You mentioned in #732 that common guile files could be
moved to some top-level directory (say, `scm/`).
Maybe it's worth moving backends there, too.

**Comment by vzh** [comment]
> Don't you consider `netlist` as one of the core
> components of the suite? :-)

Well, I think the main program in the suite is `schematic`.  All other utilities just do something useful of its results: fixing old schematics, automating changes in schematics, producing documents, images, netlists for drc, simulation, pcb layout.  Anything of this could be more tightly integrated into the program itself.  I don't understand why the user has to do many *cli* steps to do this during designing a project while we have all means to simplify this by integrating the functionality of any of the utilities into `schematic`.  Imagine using a shortcut for producing the graph of your SPICE simulation instead of running `lepton-netlist`, and then `gnucap` or `ngspice`, and then some other program to see it.  The only thing all those tools matter is automating of documentation creation (e.g. by using makefiles).  That is why most of the tools are useful (not all, I believe). `lepton-netlist` is useless without `lepton-schematic`.

BTW, for uniformity, I would move even `lepton-schematic` to `utils/` and then rename it to, say, `bin` or `tools` or `programs` :-)
 
> You mentioned in #732 that common guile files could be
> moved to some top-level directory (say, `scm/`).
> Maybe it's worth moving backends there, too.

I'm not sure if it is worth though we could try it :-) (Guile, for instance, has the `modules/` directory for its modules.  Other Scheme files are in other places.)

**Comment by graahnul-grom** [comment]
> I don't understand why the user has to do many *cli* steps
> to do this during designing a project while we have all
> means to simplify this by integrating the functionality of
> any of the utilities into `schematic`.

Yes, we have rich and well-documented Guile API.
And I have easy-to-customize "external tools" menu for that.

> Imagine using a shortcut
> for producing the graph of your SPICE simulation instead
> of running `lepton-netlist`, and then `gnucap` or `ngspice`,
> and then some other program to see it.

No need to imagine. It is reality. :-)
I've been doing exactly this for several years now:
I select a net(s), press a button and immediately see
window(s) with graph(s) drawn by the ngspice 'plot' command.

> The only thing all those tools matter is automating...

Exactly. And this is great that we have them, and not
one big integrate-them-all all-in-one program.

> BTW, for uniformity, I would move even `lepton-schematic`
> to `utils/` and then rename it to, say, `bin` or `tools`
> or `programs` :-)

Not sure I understand why do we need this.

> I'm not sure if it is worth though we could try it :-)
> (Guile, for instance, has the `modules/` directory for its
> modules. Other Scheme files are in other places.)

So, we need to compose a list of modules we should move
to that dir? Or just move all the `liblepton/scheme` there?

**Comment by vzh** [comment]
...
> No need to imagine. It is reality. :-)
> I've been doing exactly this for several years now:
> I select a net(s), press a button and immediately see
> window(s) with graph(s) drawn by the ngspice 'plot' command.

I mean this could be better integrated and available for newbies without the need of complex setup in the first place.

...
> Not sure I understand why do we need this.

Never mind, not a big deal :-)

> So, we need to compose a list of modules we should move
> to that dir? Or just move all the `liblepton/scheme` there?

I think about moving all scheme modules there, including `gui` ones, and placing the `backend/` directory in `netlist/` although the files there are not modules.

**Comment by graahnul-grom** [comment]
>> No need to imagine. It is reality. :-)
>> I've been doing exactly this for several years now:
>> I select a net(s), press a button and immediately see
>> window(s) with graph(s) drawn by the ngspice 'plot' command.

> I mean this could be better integrated and available for newbies without the need of complex setup in the first place.

Yes, I agree.
I wish it were less complex. I never thought that someday
someone except me would want to use this stuff. :-)

**Pull request merged**
