### PR TITLE
lepton-archive improvements and a new test

### PR DESCRIPTION
**Pull request by vzh**
- Output basename of the program instead of its full path on `--help`.
- Add missing `--version` description in the man page.
- Use shorter lines in the man page.
- `lepton-archive`won't copy already copied files.
- In some cases, the `gafrc` file to be updated may have no write permissions for the user.  `lepton-archive` now solves this as follows: instead of trying to append anything to it, a new file with updated contents is created after deleting the existing one.
- In cases, when renaming a file is failing, the user will now be warned that the archive created was left alone in the temp directory instead of reporting that anything was done successfully.
- A new test has been added.  It tests usage of the program with one argument which itself is a hierarchical schematic.

### CODE REVIEW

**Review by graahnul-grom — APPROVED** [review]

**Comment by graahnul-grom** [comment]
Though it's unrelated to this PR, I can't get `lepton-archive --extract`
to work with relative paths. If it's not intended to be used that way,
maybe it's worth mentioning in the man page?

**Comment by graahnul-grom** [comment]
One more unrelated point: lepton-archive man page says that
"In archive mode the program processes schematic files traversing their hierarchy, collecting and caching all subschematics, symbols and subcircuits specified in the "file=" attributes."

Shouldn't it be the "source=" attribute instead?

**Comment by graahnul-grom** [comment]
@vzh What do you think about renaming `utils/` directory
to `tools/` and moving `schematic` there? We refer to our
programs in the suite as "tools" anyway.
Though I'm not sure: it could lead to difficulties with some
git tools wrt log history.
As an example, I've created the [tb_362_rename_utils_dir](https://github.com/graahnul-grom/lepton-eda/tree/tb_362_rename_utils_dir) branch.

**Comment by vzh** [comment]
> @vzh What do you think about renaming `utils/` directory to `tools/` and moving `schematic` there? We refer to our programs in the suite as "tools" anyway. 

Please do.  I would even move Scheme scripts into `tools/scheme`, man pages into `tools/man`, etc.  It would facilitate introducing common changes in Makefiles in future.  Anyways, I like your idea.

> Though I'm not sure: it could lead to difficulties with some git tools wrt log history. As an example, I've created the [tb_362_rename_utils_dir](https://github.com/graahnul-grom/lepton-eda/tree/tb_362_rename_utils_dir) branch.

Don't worry, `git` is a very powerful program, and one who wants it, may find the history wanted.  Consider also how many renamings we have already done so far.

**Comment by vzh** [comment]
> One more unrelated point: lepton-archive man page says that "In archive mode the program processes schematic files traversing their hierarchy, collecting and caching all subschematics, symbols and subcircuits specified in the "file=" attributes."
> 
> Shouldn't it be the "source=" attribute instead?

No, the man page paragraph is correct:
```
In archive mode the program processes schematic files traversing
their hierarchy, collecting and caching all subschematics, symbols
and subcircuits specified in the "file=" attributes.
```

Traversing hierarchy means checking of the `source=` attribs.  As for subcircuits specified in the `file=` attributes, it reads about SPICE sub circuits necessary for simulation, not about `*.sch` subschematics.  You can test yourself that files specified in both attributes go into project archives.  We could add the word `SPICE` there to make the wording more accurate.  WDYT?  Please suggest your changes if you have any in mind.

**Comment by vzh** [comment]
> Though it's unrelated to this PR, I can't get `lepton-archive --extract` to work with relative paths. If it's not intended to be used that way, maybe it's worth mentioning in the man page?

Works for me.  Other way around, archiving doesn't work when I do it not from within the directory my schematics live in.  It's the limitation of our netlisting code that is used under the hood in the program.  New tests, for `lepton-archive` and `lepton-netlist` (and for other tools), even broken and disabled for now, and new code, are welcome, as always.  FWIW, my current effort is directed towards untangling relations between `libleptongui` and `liblepton` to make progress simpler to happen.

**Comment by vzh** [comment]
@graahnul-grom, please rebase and apply your renaming branch first.  I'll then rebase and apply this branch.

**Comment by graahnul-grom** [comment]
How `lepton-archive --extract` fails (for me) with relative paths:

```
$ cd tools/archive/tests/hierarchy/
$ lepton-archive sch.sch
Project archive " ... /project-archive.tar.gz" created successfully!

$ ls -l project-archive.tar.gz
-rw-r--r-- 1 dmn dmn 1247 2022-07-24 13:21  project-archive.tar.gz

$ mkdir EXT
$ cd EXT
$ lepton-archive --extract ../project-archive.tar.gz
gunzip: can't stat: ../project-archive.tar.gz: No such file or directory
tar: Error opening archive: Failed to open '../project-archive.tar'
Cannot delete file "../project-archive.tar".
system-error: ("delete-file" "~A" ("No such file or directory") (2))

$ ls -l
-rw-r--r-- 1 dmn dmn 1247 2022-07-24 13:22  project-archive.tar.gz
```

**Comment by graahnul-grom** [comment]
Another strange effect I get with `--extract` when I pass
full path to the archive:

```
$ lepton-archive --extract \
  $lepton/lepton.git/tools/archive/tests/hierarchy/project-archive.tar.gz

$ ls -l
drwxr-xr-x 3 dmn dmn  512 2022-07-24 14:48  hierarchy/
-rw-r--r-- 1 dmn dmn 1245 2022-07-24 14:48  project-archive.tar.gz

$ ls -l ../
drwxr-xr-x 3 dmn dmn 512 2022-07-24 14:48  EXT/
drwxr-xr-x 2 dmn dmn 512 2022-07-24 09:04  sym/
-rw-r--r-- 1 dmn dmn  76 2022-07-24 09:04  gafrc
-rw-r--r-- 1 dmn dmn 299 2022-07-24 09:04  sch.sch
-rw-r--r-- 1 dmn dmn 259 2022-07-24 09:04  sub.sch
-rw-r--r-- 1 dmn dmn 318 2022-07-24 09:04  subsub.sch
```

i.e. `project-archive.tar.gz` file was moved to directory
where `lepton-archive` is run. Is this intended?

**Comment by vzh** [comment]
> How `lepton-archive --extract` fails (for me) with relative paths:

Thanks for the detailed info on how to reproduce the bug!  Now I see it.  Could you please open a new issue about it to not get it lost?

**Comment by vzh** [comment]
> i.e. `project-archive.tar.gz` file was moved to directory where `lepton-archive` is run. Is this intended?

Yes, AFAIUI, it was intended in the initial Python version of the script by Stuart Brorson.  `lepton-archive` just mimicked its behaviour.  We can change it (the behaviour) at any time if there is agreement on that.

**Pull request merged**
