### PR TITLE
Get rid of the module (netlist traverse)

### PR DESCRIPTION
**Pull request by vzh**
The patch set includes the changes as follows:
- Refactoring.
- The module `(netlist traverse)` does not exist any more. All its functions have been moved to other appropriate modules.
- Fixed or added several comments and docstrings.
- Refdeses are now created on the post-process stage.
- The module `(netlist subschematic)` now contains the function `page-list->hierarchical-subschematic()`.  It is aimed to create hierarchical subschematics from lists of pages.
- Separated subschematic creation and processing of virtual pins.
- Splitted up naming of pins and finding their connections.
- Procedures working with `<pin-net>`s have been moved to the `(netlist pin-net)` module.
- Page contents is filtered once to make connections.
- Hierarchical names are now used for subschematics.
- Removed the `tag` field from the `<schematic-component>` record.  A new field, `parent`, has been added to get the same data.  For a component, it contains the link to the `<subschematic>` instance the component belongs to.
- Removed the `tag` field from the `<schematic-connection>` record.  A new field, `parent`, has been added to get the same data.  For a connection, it contains the link to the `<subschematic>` instance the connection belongs to. 
- Removed the unused `sources` field from the `<package>` record.
- Removed the unused `tag` field from the `<package>` record.

### CODE REVIEW

**Comment by vzh** [comment]
Lots of stuff, I know. However, since it is not breaking any tests, (and, I hope any one commit is transparent for the reader), I am going to apply the patch-set ASAP. Will be glad to see any comments, suggestions, and anything

**Comment by graahnul-grom** [comment]
@vzh Now I'm making a PR that starts `gafrc` settings migration, after
that I'll test your changes. Will also look at the `lepton-archive`patches (#535).

**Comment by graahnul-grom** [comment]
AFAICS, all works fine. A large amount of work.
Though I see netlist still complaining about nets shorted to themselves.
Couldn't [this](https://github.com/lepton-eda/lepton-eda/issues/483#issuecomment-570312078) fix it?

**Comment by vzh** [comment]
For now, it can be fixed with your patch (please make a PR on this). In future, I'm planning to get rid of all inherited renaming stuff, though.

**Pull request merged**
