### PR TITLE
Get rid of nc.doc. Move its contents into manual.

### PR DESCRIPTION
**Pull request by vzh**
Affects #732.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
@vzh
Володь, с праздником!
What's wrong with `make pdf`?

**Comment by graahnul-grom** [comment]
`make distcheck` runs fine, but
```
$ make -C docs/manual/ pdf
  TEXI2PDF lepton-manual.pdf
/usr/local/bin/texi2dvi: pdfetex exited with bad status, quitting.
*** Error code 1

Stop.
make: stopped in /home/dmn/lepton/lepton.git/docs/manual
```

**Comment by vzh** [comment]
It works eventually :-)

**Review by graahnul-grom — APPROVED** [review]
Yes, it works. :-)

**Pull request merged**
