### PR TITLE
Get rid of OBJ_PLACEHOLDER

### PR DESCRIPTION
**Pull request by vzh**
This ad hoc type always irritated me :-)  Hope the code is now simplified a little.

### CODE REVIEW

**Review by graahnul-grom — APPROVED** [review]
Much better now w/o that placeholder pseudo-component.
:+1:

**Comment by graahnul-grom** [comment]
> OBJ_PLACEHOLDER type.  The type value is still preserved in
> o_type.h to support deprecated Scheme code.

Could you please point me at the deprecated
Scheme code that uses that placeholder type?

**Comment by vzh** [comment]
The `OBJ_PLACEHOLDER` symbol is defined in `liblepton/src/scheme_deprecated.c` and **may** be used in `libleptongui/scheme/default-attrib-positions.scm`.

**Comment by graahnul-grom** [comment]
Thank you

**Pull request merged**
