### PR TITLE
Do not use deprecated (geda config) module

### PR DESCRIPTION
**Pull request by graahnul-grom**

### CODE REVIEW

**Comment by vzh** [comment]
Thank you!
As you can see, superfluous spaces make git-grepping not such successful :-)

**Comment by graahnul-grom** [comment]
Aha, `DBCS` strikes back! :-)
`git grep 'geda config'`? No!
`git grep -E 'geda +config'`!

**Comment by vzh** [comment]
... strikes back via YOUR code ;-) so its your style. And don't tell me about other languages, the same happened with many people before more than once during refactoring.
Using `git grep -E` is annoying.

**Comment by graahnul-grom** [comment]
Please do not worry, I'm just kidding. :)
`grep -E` is awkward, I agree.

**Pull request merged**
