### PR TITLE
Remember the last chosen file filter in Open and Save dialogs

### PR DESCRIPTION
**Pull request by graahnul-grom**
`Open` and `Save As` dialog boxes now remember the
last chosen file filter. Previously, they always
opened with schematic files (*.sch) filter set.

### CODE REVIEW

**Comment by vzh** [comment]
@graahnul-grom Thank you!

**Comment by vzh** [comment]
@graahnul-grom BTW, do you plan to delete your merged branches, or you store them on purpose? They just clutter git history a little.

**Comment by graahnul-grom** [comment]
@vzh The purpose of these branches is to keep track of what I have done. Although, I could keep them just in the local repository.

**Comment by vzh** [comment]
OK. I just wanted to say that for me, and for people like me who follow/review your work, it's sometimes not easy to understand, what branches are still need to be reviewed or are already merged, without consulting with github, and [here](https://github.com/lepton-eda/lepton-eda/network) people could think there are many not reviewed branches.

**Comment by graahnul-grom** [comment]
@vzh I have deleted the stale remote branches, as you suggested. Keep them locally.

**Comment by vzh** [comment]
Thank you :-)

**Pull request merged**
