### PR TITLE
Fix g++ compilation warnings in several utils

### PR DESCRIPTION
**Pull request by vzh**

### CODE REVIEW

**Comment by graahnul-grom** [comment]
@vzh Do you get many `-Wformat-overflow` warnings on `sprintf()` calls too?

**Comment by vzh** [comment]
> @vzh Do you get many `-Wformat-overflow` warnings on `sprintf()` calls too?
> (`convert_sym.c`)

No, I haven't seen them on my machines. Are they the result of my commits above or were there before?

**Comment by graahnul-grom** [comment]
They were there before

**Comment by graahnul-grom** [comment]
Another 7 warnings while building `contrib/` with `clang 6.0.1` on `FreeBSD 11.2-STABLE`:

1:
```
gmk_sym.c: In function 'make_pin':
gmk_sym.c:558:3: warning: 'strncpy' output may be truncated copying 5 bytes from a string of length 39 [-Wstringop-truncation]
   strncpy(pin_used[pin_counter++],pin,5);    /* save the current pin, the first 5 char */
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2:
```
convert_sym.c: In function 'attribute_object':
convert_sym.c:1890:21: warning: '%s' directive writing up to 1023 bytes into a region of size between 0 and 1023 [-Wformat-overflow=]
   sprintf(text, "%s=%s", tmpName, tmpValue);
                     ^~            ~~~~~~~~
convert_sym.c:1890:3: note: 'sprintf' output between 2 and 2048 bytes into a destination of size 1024
   sprintf(text, "%s=%s", tmpName, tmpValue);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

3:
```
convert_sym.c: In function 'do_instance':
convert_sym.c:1559:24: warning: '%d' directive writing between 1 and 11 bytes into a region of size between 0 and 1023 [-Wformat-overflow=]
   sprintf(symName, "%s-%d.sym",name,extension);
                        ^~
convert_sym.c:1559:20: note: using the range [-2147483648, 2147483647] for directive argument
   sprintf(symName, "%s-%d.sym",name,extension);
                    ^~~~~~~~~~~
convert_sym.c:1559:3: note: 'sprintf' output between 7 and 1040 bytes into a destination of size 1024
   sprintf(symName, "%s-%d.sym",name,extension);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

4:
```
convert_sym.c: In function 'do_label':
convert_sym.c:1362:31: warning: '%s' directive writing up to 1023 bytes into a region of size 1015 [-Wformat-overflow=]
       sprintf(text, "pinlabel=%s", text2);
                               ^~   ~~~~~
convert_sym.c:1362:7: note: 'sprintf' output between 10 and 1033 bytes into a destination of size 1024
       sprintf(text, "pinlabel=%s", text2);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

5:
```
convert_sym.c:1353:29: warning: '%s' directive writing up to 1023 bytes into a region of size 1017 [-Wformat-overflow=]
       sprintf(text, "refdes=%s", text2);
                             ^~   ~~~~~
convert_sym.c:1353:7: note: 'sprintf' output between 8 and 1031 bytes into a destination of size 1024
       sprintf(text, "refdes=%s", text2);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

6:
```
convert_sym.c:1343:30: warning: '%s' directive writing up to 1023 bytes into a region of size 1016 [-Wformat-overflow=]
       sprintf(text, "netname=%s", text2);
                              ^~   ~~~~~
convert_sym.c:1343:7: note: 'sprintf' output between 9 and 1032 bytes into a destination of size 1024
       sprintf(text, "netname=%s", text2);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

7:
```
convert_sym.c: In function 'do_attached_attribute':
convert_sym.c:840:32: warning: '%s' directive writing up to 1023 bytes into a region of size 1014 [-Wformat-overflow=]
       sprintf(text, "pinnumber=%s", &text2[2]);
       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
convert_sym.c:840:7: note: 'sprintf' output between 11 and 1034 bytes into a destination of size 1024
       sprintf(text, "pinnumber=%s", &text2[2]);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by vzh** [comment]
@graahnul-grom, I don't use clang so don't see them. Fix them if you want. However, I should say that those little utils are subjects for rewriting in Scheme or throwing out (if their value is as little as their size).

**Pull request merged**
