### PR TITLE
Tabbed GUI support

### PR DESCRIPTION
**Pull request by graahnul-grom**
Display each schematic in its own tab if `use-tabs` configuration
key (`[schematic.gui]` group) is set to `true`.
For other options and comments, please take a look at
the top of a new [schematic/src/x_tabs.c](https://github.com/graahnul-grom/lepton-eda/blob/tb_021_x_tabs/schematic/src/x_tabs.c) file.

ss0

### CODE REVIEW

**Comment by vzh** [comment]
Hi @graahnul-grom, I like this PR very much!
I haven't reviewed your code thoroughly yet though found some little issues in it. Would be nice if you fix them.
Please look [at this fix for C++ compiler](https://github.com/vzh/lepton-eda/commit/8270f652e949fb904a57ec4dc052a6ad7170550c).
And please avoid C++ style comments ('//' ;-)) as is described in CONTRIBUTING.md.

Thanks!

**Comment by graahnul-grom** [comment]
Indeed. Somehow, I forgot to check it with C++ compiler, my bad. Thank you!
Cannot find any of those criminal-style comments in my code. :)
Except maybe within `x_tabs.c` file's header comment block. Do I need to remove them too?

**Comment by vzh** [comment]
Oh, I'm sorry for my superficial look at this. No need to remove comments within comments :-)

**Comment by graahnul-grom** [comment]
Please tell me, what's the best way to deal with your fix? Do I have to correct the code myself and push to the `tb_021_x_tabs` branch? Or maybe download the patch from the link above and `git am` it and then push the changes?

**Comment by vzh** [comment]
I'm fine with anything you choose :-) Please do what you like better or what is easier/more convenient for you.

**Comment by vzh** [comment]
@dmn In commit b95c3bf you use functions from GDK 2.24 while we yet require 2.18 in `configure.ac`. Do you think it's time to bump the required version of GDK? Is this a relevant change in this series?

**Comment by graahnul-grom** [comment]
GTK+ 2.24 (the latest branch in 2x series) was started in 2011.
I think it is safe to use it.

**Comment by vzh** [comment]
@graahnul-grom Since your changes are complex enough and I see no serious issues in them I am going to merge them as is except for the above mentioned commit (which is not relevant here). I strongly recommend you to make two additional PRs if you want to bump the version of GTK+ in lepton in order to make the change distinct and visible for others: 1) a PR with bumping the version of GTK+/GDK and 2) a PR with the commit in question. Those two PRs could be merged before this one, I believe, to avoid reverting here.
Thanks.

**Comment by vzh** [comment]
OK, I've done the two PRs myself :-)

**Comment by graahnul-grom** [comment]
Опередили! :)

**Comment by vzh** [comment]
@graahnul-grom Thank you for your work!
It would be also great if you prepare a summary for this PR to include in *NEWS*.

**Comment by graahnul-grom** [comment]
OK

**Comment by graahnul-grom** [comment]
Tabbed GUI support has been added: each schematic page
can be displayed in its own tab within GtkNotebook widget.
It is disabled by default, and can be turned on by setting
`schematic.gui::use-tabs` configuration key to `true`.
There are other options related to tabbed GUI:
`schematic.tabs::show-close-button`, `schematic.tabs::show-up-button`
determines whether to show "close" and "hierarchy up" buttons
on each tab, respectively.

**Pull request merged**
