### PR TITLE
Replace 2 obsolete utils with a new one

### PR DESCRIPTION
**Pull request by vzh**
This commit set replaces two obsolete utils -- `gschupdate` and `gsymupdate` -- with a new one: `lepton-update`.

The reasons are as follows:
- old utilities have names conflicting with those in *geda-gaf* installation
- they are sort of broken as call for obsolete `gschlas` name inside them
- they just parse text without using Lepton library so their facilities are limited.

The new utility is better:
- it does better job by using `liblepton` so updates files better, you can look at the commit history to learn how the job improved
- one file instead of two
- well documented (in the man page and in the texinfo manual)
- well tested
- has new options: `--help` and `--version` as other tools have.

The integration test suite has been improved to contain new utility macros in Scheme which aid in testing of various command-line options.

The utility can be extended further and probably merged with other tools, e.g. `lepton-symfix` etc.  The name may be discussed as well.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
`make distcheck` failed for me, three tests for `lepton-update`:

```
FAIL: tests/update.test - update-files [4]
FAIL: tests/update.test - update-files [5]
FAIL: tests/update.test - update-files [6]
```

**Comment by vzh** [comment]
@graahnul-grom, could you elaborate more on it please?
To find details, open the `tests` directory in your build directory.  E.g. on my system with out-of-source build I open `~/tmp/build/lepton-eda/lepton-eda-1.9.16/_build/sub/tests/`.  It contains log files for the build with some debugging info which may look like as follows:
```
Test: diff /home/vzh/tmp/build/lepton-eda/lepton-eda-1.9.16/_build/sub/run.update.test/net-attribute.sch /home/vzh/tmp/build/lepton-eda/lepton-eda-1.9.16/_build/sub/run.update.test/net-attribute.sch.upd
test-name: #f
location: update.test:90
source:
+ (test-eq
+   EXIT_SUCCESS
+   (status:exit-val
+     (system* "diff" test-copy golden-copy)))
1c1
< v 20210731 2
---
> v 20210626 2
expected-value: 0
actual-value: 1
result: FAIL
```

As you can see, all absolute paths are provided in the `diff` command.  So you can investigate the issue further by just probing the command and/or looking at the files processed.

**Comment by graahnul-grom** [comment]
From `tests/update.log`:
```
test-name: #f
location: update.test:90
source:
+ (test-eq
+   EXIT_SUCCESS
+   (status:exit-val
+     (system* "diff" test-copy golden-copy)))
expected-value: 0
actual-value: 1
result: FAIL

test-name: #f
location: update.test:90
source:
+ (test-eq
+   EXIT_SUCCESS
+   (status:exit-val
+     (system* "diff" test-copy golden-copy)))
expected-value: 0
actual-value: 1
result: FAIL

test-name: #f
location: update.test:90
source:
+ (test-eq
+   EXIT_SUCCESS
+   (status:exit-val
+     (system* "diff" test-copy golden-copy)))
expected-value: 0
actual-value: 1
result: FAIL
```

**Comment by graahnul-grom** [comment]
Just before `test-run-success()` on line 90 in `update.test`
I see the following commands:
```scheme
(system* "sed" "-i" "1d" test-copy)
(system* "sed" "-i" "1d" golden-copy)
```

Non-GNU `sed` doesn't work without `-e` before the expression,
should be:

```scheme
(system* "sed" "-i" "-e" "1d" test-copy)
(system* "sed" "-i" "-e" "1d" golden-copy)
```

After the change `make distcheck` runs fine on my system.

**Comment by graahnul-grom** [comment]
BTW, it seems that `make -C utils/update/tests/ check`
command does not run anything. Strange.

**Comment by graahnul-grom** [comment]
I was wrong explaining the `sed -i -e` command.
Actually, non-GNU `sed` requires a parameter for the `-i`
switch - an extension of the backup file it creates after
"in-place" editing.
So, portable commands should look like these:

```scheme
(system* "sed" "-i.bak" "-e" "1d" test-copy)
(system* "sed" "-i.bak" "-e" "1d" golden-copy)
```

**Comment by graahnul-grom** [comment]
Nope! :)

```
(system* "sed" "-ibak" "-e" "1d" test-copy)
(system* "sed" "-ibak" "-e" "1d" golden-copy)
```
(`-ibak` without dot. `make distcheck` fails with `-i.bak`)

**Comment by vzh** [comment]
@graahnul-grom, please check if it works now on your system.  I've applied the changes you suggested.

**Review by graahnul-grom — APPROVED** [review]
Yes, it works now on FreeBSD.

**Pull request merged**
