### PR TITLE
GTK3: get rid of warnings on using deprecated GtkAlignment objects.

### PR DESCRIPTION
**Pull request by vzh**

### CODE REVIEW

**Comment by graahnul-grom** [comment]
Although the patch set eliminates the warnings, it also
affects the dialog resize behavior.

GTK2:
pr_865_gtk2

GTK3:
pr_865_gtk3

The same with other dialogs.
Also, the vertical splitter in the Add Component dialog
doesn't work anymore.

Is there any replacement for GtkAlignment in GTK3?

**Comment by vzh** [comment]
I haven't found any one yet.  Probably some widget expand functions will help. I'll look into that later.

**Review by graahnul-grom — APPROVED** [review]

**Comment by vzh** [comment]
It seems, `gtk_widget_set_hexpand()` should do the trick.  I used it before, e.g. for *Add text* dialog. The question is, what widget(s) should be expanded.

**Comment by graahnul-grom** [comment]
I think those expandable in GTK2 version.

**Comment by vzh** [comment]
@graahnul-grom, I seem to have fixed the issues you've mentioned above (at least, the widgets resize correctly in my WM).  Could you please try it on your system once again?

**Comment by graahnul-grom** [comment]
Sorry for the delay.
All dialogs are OK now, except the "Edit properties" one.

2022-01-16-233741_591x438_scrot

**Comment by vzh** [comment]
Fixed in the last commit.  Thanks!

**Comment by graahnul-grom** [comment]
Thank you. I think it's time to merge this PR.

**Pull request merged**
