### PR TITLE
init commit for analog sims (new fork)

### PR DESCRIPTION
**Pull request by drforbin**
Vlad, 

I got sick of fighting this and deleted my repo and re-forked.
I have added all the initial analog sims with models and a symbol generation file gmk-sym.
Please have a look and give me feedback.
I'll be writing a wiki and adding in next few days.

DF

Affects #156

### CODE REVIEW

**Comment by drforbin** [comment]
IT PASSED!

**Comment by vzh** [comment]
In addition to what @graahnul-grom has said, please remove those files and do `git commit --amend` and then `git push --force-with-lease` instead of making a new commit. Otherwise, those two files go to the repository, which is not what we would want.

**Comment by drforbin** [comment]
I'll change it. But you understand there is a reason I left those files in place.
The two analog examples were exactly real projects. They were used to fix my FRG-7700 ham radio.I thought the inclusion of the files would be a nice reference touch.

DF

**Comment by drforbin** [comment]
Ok. I did it.

**Comment by vzh** [comment]
I've cleaned up your branch, squashed changes and merged it.

**Pull request closed without merging**
