### PR TITLE
Add 'spice-noqsi' backend to the repository.

### PR DESCRIPTION
**Pull request by vzh**
For now, it's just merged as a whole project living in a separate directory :-)  Some TLC is needed to fully integrate it to the repository, though.

### CODE REVIEW

**Comment by vzh** [comment]
Hi there,
I'd like to merge the branch ASAP in order to avoid new merges.
Opinions?

**Comment by graahnul-grom** [comment]
Looks good to me.
`make distcheck` is OK.
Why github shows "This branch cannot be rebased due to conflicts"?
I've tried to merge the branch locally with `git merge --ff-only vzh-spice-noqsi` and it merges without errors.

**Comment by vzh** [comment]
Спасибо, Дим!
We don't know the logic GH uses when doing its internal checks.  So, this doesn't matter.
What matters is the fact that the nice backend by John Doty is now merged and I would propose to release a new *major* version of Lepton :-) (... despite other issues we have yet, with docs etc.)

**Comment by graahnul-grom** [comment]
Not sure about a *major* version, but it's certainly time to make
a release, considering also tremendous amount of work put into
finally fixing the longstanding font rendering issues (it's not only
about problems with recent version of `pango`).

**Comment by graahnul-grom** [comment]
@vzh Didn't you read our `gitter` recently?
May I add a `Fedora` page to out wiki?

**Comment by vzh** [comment]
Of course, it's **our** wiki, not my own :-)
About gitter, they used to send me email notifications of news there.  For some reason, I didn't see anything about the last additions though.

**Comment by graahnul-grom** [comment]
`gitter` email notifications stop working for me, too.

**Pull request merged**
