### PR TITLE
Add various tests for "no-connect" symbol

### PR DESCRIPTION
**Pull request by vzh**

### CODE REVIEW

**Comment by graahnul-grom** [comment]
After merging #263 and then #264, one of `make check` tests fail:
```
> make -C netlist/ check
...
FAIL: drc2/connected-noconnects-geda.out
...
```

That is because I changed `geda` backend output in #263.
Here's the diff that makes this test succeed:

```diff
diff --git a/netlist/tests/drc2/connected-noconnects-geda.out b/netlist/tests/drc2/connected-noconnects-geda.out
index 0aea27acc..3ad8447e5 100644
--- a/netlist/tests/drc2/connected-noconnects-geda.out
+++ b/netlist/tests/drc2/connected-noconnects-geda.out
@@ -1,7 +1,7 @@
 START header
 
-gEDA's netlist format
-Created specifically for testing of gnetlist
+Lepton EDA netlist format
+Created specifically for testing of lepton-netlist
 
 END header
 
```

[264_geda_out.diff.txt](https://github.com/lepton-eda/lepton-eda/files/2509708/264_geda_out.diff.txt)

**Comment by vzh** [comment]
(just wanted to comment your this code in #263 :-))
I'm particularly not sure about those two lines.
First, the backend name is still `geda`.
Second, it has been created namely to test `gnetlist`, hasn't it?

**Comment by graahnul-grom** [comment]
Indeed, `Initially created for testing of gnetlist` is better.
However, I've already changed all of the `*.out` files (so that `make check` test pass).
Now we need to revert/alter all of them:

```
> cd netlist/tests
> find . -name '*.out' | xargs grep --color "gEDA's netlist format" | wc -l
35
```

**Comment by vzh** [comment]
@graahnul-grom, I've already done that in #265. Please review it first.

**Pull request merged**
